### ISSUE TITLE
Integrate in PHP

### ISSUE THREAD

**Issue by chrisdaloa** [RadValentin/rss-2-alexa-flash-briefing-json#3]
Hi, How can I use it in a apache server (php page) ? Thank you.

**Comment by RadValentin** [comment]
It should be easier to implement in PHP what this repo does with Node, just have your code pull in a RSS feed and spit out a JSON object with the fields mentioned in the [Alexa Flash Briefing Skill API](https://developer.amazon.com/docs/flashbriefing/flash-briefing-skill-api-feed-reference.html#feed-format-details)

**Comment by RadValentin** [comment]
Closing this for now, feel free to reopen if you need more info
